### ISSUE TITLE
Orbkit connection problem

### ISSUE THREAD

**Issue by Quark195** [felixplasser/theodore-qc#26]
Dear developers!
I really liked your program and I wanted to use it further in my research. However, I ran into a problem while installing. I can't connect Orbkit with Theodore. After adding commands to .bashrc,
`export ORBKITPATH=$HOME/orbkit
export PYTHONPATH=$PYHONPATH:$ORBKITPATH
`
the following error occurs:
`
Traceback (most recent call last):
  File "/home/quark/.local/bin/theodore", line 5, in <module>
    from theodore import run
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/__init__.py", line 1, in <module>
    from .actions import run
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/__init__.py", line 2, in <module>
    from .analyze_tden import AnalyzeTden, AnalyzeTdenUnr
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/actions/analyze_tden.py", line 4, in <module>
    from .. import theo_header, lib_tden, lib_exciton, input_options
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/lib_tden.py", line 8, in <module>
    from . import orbkit_interface, fchk_parser
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/orbkit_interface.py", line 17, in <module>
    from .orbkit_full import lib_orbkit
  File "/home/quark/.local/lib/python3.8/site-packages/theodore/orbkit_full.py", line 14, in <module>
    from orbkit import read,grid,core,output,options
ImportError: cannot import name 'read' from 'orbkit' (unknown location)
`

 I installed the Theodore program 
` pip3 install Theodore`
 I installed the Orbkit program according to the manual from https://github.com/felixplasser/orbkit. As stated in the manual, there is an alternative way to render orbitals NTO using VMD. Unfortunately, I cannot figure out how to use this script for rendering. I use Orca 5.0 TDDFT calculation files as input.
 By the way, I found that the version of the file is 2.5.0 in pip, but it is displayed as 2.4.0.
I hope you'll give me a hand.

Best regards,
Eugene

**Comment by Quark195** [comment]
Dear developers! I was able to figure out how to install Orbkit, however, I am unable to generate cube files for VMD. The problem was solved by encouraging the installation of paths as indicated here
https://sourceforge.net/p/theodore-qc/discussion/bugs_questions/thread/d385dcb3f1/
Best regards,
Eugene

**Comment by felixplasser** [comment]
Hi Eugene,

We are in the process of rewriting the user interface for TheoDORE and it is taking a bit longer than I had hoped. I am not quite sure what the state of the version on `pip3` is. Maybe @MFSJMenger could tell use more?

The last fully tested version is TheoDORE 2.4 and you can get this from the github Releases or via sourceforge. Maybe that is a good starting point.

Anyway, I'll have a look at this issue soon.

-Felix
