### ISSUE TITLE
Malfunctioning interface to TDDFT calculations with TURBOMOLE 7.7

### ISSUE THREAD

**Issue by adam-srut** [felixplasser/theodore-qc#37]
Dear developers,
The TheoDORE3.0 interface is not compatible with the output from escf module of TURBOMOLE v7.7.
The problem seems to be on line 450 of file_parser.py. The word 'excitation' will appear multiple times in the header of escf.out file in v7.7.

Would be also possible to add support for calculations with unrestricted wavefunction? That is, file unrs_a has to be parsed instead of sing_a or trip_a files.

Kind regards,
Adam

**Comment by adam-srut** [comment]
Hi Felix, thank you for the quick reaction!
I only changed line 450 to:
`    if 'excitation' in line and not 'vector' in line and not 'energies' in line:`
the `analyze_tden` seems to be working now.
I will be looking forward to the new features then!
All the best, Adam

**Comment by felixplasser** [comment]
Ok, great! This does not seem to break any of the existing tests. So let's take into the main code :)
