### ISSUE TITLE
molden files and orbkit

### ISSUE THREAD

**Issue by Audiochemie** [felixplasser/theodore-qc#48]
Hi Felix, thanks for the nice program. It is really helpful!

I ran into trouble though trying to compute particle hole densities and transition densities with the orbkit interface.

```python 
  File "xxx/TheoDORE_3.1.1/theodore/lib_tden.py", line 745, in compute_rho_0_n
    cube_ids=lib_orbkit.compute_rho_0_n(
  File "xxx/TheoDORE_3.1.1/theodore/orbkit_full.py", line 139, in compute_rho_0_n
    qc = self.orbkit_geo_ao_conversion(mos, molden_file=molden_file)
  File "xxx/TheoDORE_3.1.1/theodore/orbkit_full.py", line 47, in orbkit_geo_ao_conversion
    qc = read.read_molden(tmp)
  File "xxx/orbkit/orbkit/read/molden.py", line 370, in read_molden
    sym = sym[0].split('.')[-1]
```
Presumably this is linked to the fact that not the molden file specified in the input is used, but a temporary file which only contains the molden file header and a bit of a mo section. 
orbkit fails to read as it (rightfully) awaits mo coefficients. As I do not see a good reason for a temporary file to be passed to orbkit, I'd suggest to simply use the molden file specified by the user this should fix the issue.

Best regards 
Timo

**Comment by felixplasser** [comment]
Hi Timo, I am happy to have a look at that if you upload the full set of files TheoDORE reads.

The orbkit interface is not super robust. So, there might be an easy fix ...

**Comment by felixplasser** [comment]
Hi, I had a look at this. In the first instance this tells me
~~~~
FileNotFoundError: [Errno 2] No such file or directory: 'singlet1.in.out'
~~~~
So, I guess we'd need that file as well.

Does the test work for you.
~~~~
cd EXAMPLES
pytest-3 EXTRA/fa2.orbkit
~~~~

**Comment by Audiochemie** [comment]
Whoops... I renamed the file to mrci.log and didn't change it in the `dens_ana.in`. Don't know why I did that. Here's a - hopefully - working archive: 
[theodore_troubleshooting.tar.gz](https://github.com/felixplasser/theodore-qc/files/13355452/theodore_troubleshooting.tar.gz)
The test fails with the same error message as posted above.

**Comment by felixplasser** [comment]
Ok, if the test also fails, then this indicates a problem with the installation or orbkit version. I had a go with your files. It all works. As a proof I am attaching some figures made with [qc_pymol](https://github.com/felixplasser/qc_pymol). 
![rho_0_1b1](https://github.com/felixplasser/theodore-qc/assets/15384858/8f61e97b-b7d9-4115-a19e-3f9f1cba4754)
![rho_0_1b2](https://github.com/felixplasser/theodore-qc/assets/15384858/b38d6ac5-9cd9-45fe-b54d-1483801ac16f)
![rho_0_1a2](https://github.com/felixplasser/theodore-qc/assets/15384858/1944980c-55a2-4e87-a3c4-805b8a70f89a)

**Comment by felixplasser** [comment]
Maybe the safest way to do it is to clone the git repo with all the same versions that I am using
`git clone --recursive https://github.com/felixplasser/theodore-qc.git`

This sets symlinks to orbkit and cclib.

Then you install orbkit as described here
https://theodore-qc.sourceforge.io/docs/installation.html#external-packages

Do you want to give this a go?

**Comment by Audiochemie** [comment]
A reinstall with the recursively cloned repo worked. :-)
