### ISSUE TITLE
TheoDORE Calculation is not finishing

### ISSUE THREAD

**Issue by AvinashHari123** [felixplasser/theodore-qc#49]
Dear Sir,
TheoDORE calculation with the given keywords is not finishing. The calculation starts and at some point gets stuck even though it shows the calculation is running. What could be a possible remedy for the issue. The molecule being used is a dimer relatively large with 64C and 40H.

~~~~
%nprocshared=28
%mem=120GB
%chk=AB_WB9.chk
# td=(50-50,nstates=10) wb97xd/6-311+g(d,p) pop=full gfinput iop(9/40=3,3/33=4)
~~~~

**Comment by felixplasser** [comment]
Hi, thanks for writing. What do you mean exactly? The Gaussian job finishes and then TheoDORE gets stuck? I am happy to have a look if you post the gaussian log file and the TheoDORE input file here.
