### ISSUE TITLE
Representing orbital figures using Jmol

### ISSUE THREAD

**Issue by Jong-hwan-Lee** [felixplasser/theodore-qc#53]
Hello. I'm trying to draw orbital and density figures from TDDFT results by Q-Chem.

Following this site (https://theodore-qc.sourceforge.io/docs/orbitals_and_densities.html), after running 'analyze_tden', I got nto_jmol.spt file.
So I downloaded Jmol program and tried to run this file but it didn't work well.
When I type 'load MOs.mld FILTER "nosort"' command in console, the error message was occurred like below.

> $ load MOs.mld FILTER "nosort"
Error reading file at line 1269526:
Sym= X
1123
for file C:/Users/Jonghwan/Desktop/Eom/QChem/MOs.mld
type Molden

So I asked this problem to Jmol developer and he replied like below.

> Thanks - It's an array out of bounds exception. It's due to an errant second [GTO] label just before the [MO] line. This resets the basis and sets the number of coefficients to 0.
[GTO]
....
[GTO]
[MO]
 Sym= X
But in addition to that, there are 916 coefficients defined in [GTO], but there are 1124 coefficients in the MOs. So even when I take that second [GTO] out, it still fails. You have 1124 - 916 = 208 too many coefficients. 
So I don't know what is going on there.
(my guess is that it's the wrong Gaussian basis for these MOs)

Can you answer why this error is generated?
Because of the limitation of the possible uploaded file size, if you require the related files, tell me your e-mail then I will send them.

**Comment by felixplasser** [comment]
When you are running Q-Chem, then I would go via `state_analysis=true`
https://manual.q-chem.com/latest/subsec_esanacc.html

This is analogous to TheoDORE but the functionality is already integrated in Q-Chem. Generally, this is more stable and more efficient than going via TheoDORE.

The fchk file option that you seem to be using is more of a hack. It does not recognise spherical vs cartesian d- and f-functions. I guess that is what is going wrong in your case.

**Comment by felixplasser** [comment]
But my other comment: I would test all the workfows with a smaller molecule and basis set. And then you can work your way up, once you see that the basic functionality works
